#!/bin/bash

apt-get -y install php7.2
apt-get -y install php7.2-apcu
apt-get -y install php7.2-cgi
apt-get -y install php7.2-curl
apt-get -y install php7.2-gd
apt-get -y install php7.2-imap
apt-get -y install php7.2-intl
apt-get -y install php7.2-ldap
apt-get -y install php7.2-mbstring
apt-get -y install php7.2-mysql
apt-get -y install php7.2-pspell
apt-get -y install php7.2-recode
apt-get -y install php7.2-snmp
apt-get -y install php7.2-soap
apt-get -y install php7.2-tidy
apt-get -y install php7.2-xml
apt-get -y install php7.2-xmlrpc
apt-get -y install php7.2-xsl
apt-get -y install php-pear
apt-get -y install php-cas
apt-get -y install php-gettext
apt-get -y install php-imagick
apt-get -y install php-memcache
apt-get -y install perl
apt-get -y install perl-modules
apt-get -y install libapache2-mod-php7.2
apt-get -y install libapache2-mod-perl2
apt-get -y install libcompress-zlib-perl
apt-get -y install libdbd-mysql-perl
apt-get -y install libdbi-perl
apt-get -y install libnet-ip-perl
apt-get -y install libsoap-lite-perl
apt-get -y install libxml-simple-perl
